### ISSUE TITLE
[python/celery] example does not match ddtrace-run instructions

### ISSUE THREAD

**Issue by caleb15** [DataDog/trace-examples#114]
https://ddtrace.readthedocs.io/en/stable/integrations.html#celery says to do `patch(celery=True)` yet I don't see it in the example. Which one is right? Do both work? 🤔 

I tried a similar command to the example:

`ddtrace-run celery worker --app  ff --loglevel INFO --queues queueName --concurrency  2 --task-events`

but I'm not getting any APM data.

I haven't tried `patch(celery=True)` yet.

**Comment by Arseniy-Popov** [comment]
Have you managed to make it work?

**Comment by caleb15** [comment]
Yes. We prefix the celery command with ddtrace-run and we just import ddtrace. No patch required.
