### ISSUE TITLE
ruby/rails/config/initializers/datadog-tracer.rb different from the Tracer documentation

### ISSUE THREAD

**Issue by hbin** [DataDog/trace-examples#32]
Hi DataDog team,

Seems like the https://github.com/DataDog/trace-examples/blob/master/ruby/rails/config/initializers/datadog-tracer.rb
```
require 'ddtrace'

# Tracing configuration
Rails.configuration.datadog_trace = {
  auto_instrument: true,
  auto_instrument_redis: true,
  auto_instrument_grape: true,
  default_service: ENV['RAILS_SERVICE'] || 'rails-local',
  default_database_service: ENV['RAILS_MYSQL_SERVICE'] || 'db-local',
  default_cache_service: ENV['RAILS_CACHE_SERVICE'] || 'cache-local',
  default_controller_service: ENV['RAILS_CONTROLLER_SERVICE'] || 'controller-local',
  trace_agent_hostname: ENV['DATADOG_TRACER'] || 'datadog'
}
```

is different from the http://gems.datadoghq.com/trace/docs/#Ruby_on_Rails:

```
Datadog.configure do |c|
  c.use :rails, options
end
```

Is the example outdated?

**Comment by palazzem** [comment]
@hbin hello! yes the example is definitely outdated. It's part of our work to redact this entire repository to provide also benchmarks and ready to deploy applications. Sorry for that!

Anyway, the latest snippet you wrote (from the documentation) is the right one.

**Comment by hbin** [comment]
ic, thank you for your response.
